name: SHKTown
version: 1.0
main: kr.shkworld.shktown.SHKTown
api-version: 1.21

commands:
  돈:
    description: 플레이어가 가진 돈을 확인합니다.
    usage: /돈 [순위] [페이지]
    aliases: [ehs]

  마을:
    description: 마을 정보를 확인합니다.
    usage: /마을
    aliases: [akdmf]

  재산:
    description: 플레이어가 가진 재산을 확인합니다.
    usage: /재산 [순위] [페이지]
    aliases: [wotks]

  캐시:
    description: 플레이어가 가진 캐시를 확인합니다.
    usage: /캐시
    aliases: [zotl]