name: SHKTown
version: 1.0
main: kr.shkworld.shktown.SHKTown
api-version: 1.21

soft-depend: [LuckPerms, WorldGuard]

commands:
  shktown:
    description: SHKTown 관리 명령어
    usage: /shktown
    aliases: [shk]

permissions:
  shktown.admin:
    description: SHKTown 관리자 권한
    default: op
  shktown.shop.open:
    description: 시스템 상점 열기 권한
    default: true
